"""Parse the halimbahae/Hadith corpus into staging Parquet.

halimbahae/Hadith lays out one directory per book, each holding a plain CSV and
a ``*_mushakkala*.utf8.csv`` variant carrying full Arabic diacritics (tashkeel).
We parse the diacritised variant: the headerless ``"<number>","<text>"`` rows
are read with autogenerated column names so the first row is not consumed as a
header, then the text is cleaned **while preserving tashkeel** — only the stray
bidi control marks (U+200E/U+200F) the corpus scatters between words and the
redundant whitespace are removed, so the diacritics that distinguish this source
survive into ``full_text_ar`` (consistent with ``src.utils.arabic`` normalisers,
which strip diacritics only for the canonical name-matching path, never here).
"""

from __future__ import annotations

import re
from pathlib import Path

import pyarrow as pa
import pyarrow.csv as pcsv

from src.parse.base import generate_source_id, safe_int, safe_str, write_parquet
from src.parse.collection_metadata import apply_collection_metadata
from src.parse.schemas import COLLECTION_SCHEMA, HADITH_SCHEMA
from src.utils.arabic import clean_whitespace
from src.utils.logging import get_logger

logger = get_logger(__name__)

SOURCE_CORPUS = "halimbahae"
SECT = "sunni"

# The diacritised variant is marked by ``mushakkala`` (vocalised) in the filename.
_DIACRITICS_RE = re.compile(r"mushakkala|tashkeel|diacritics", re.IGNORECASE)

# Bidi control marks (LRM/RLM and the embedding/override/isolate family) that the
# corpus sprinkles between words as visual separators — formatting, not meaning,
# so they are removed while every tashkeel mark is kept.
_BIDI_CONTROL_RE = re.compile("[\u200e\u200f\u202a-\u202e\u2066-\u2069]")


def _clean_preserving_diacritics(text: str) -> str:
    """Strip bidi control marks and collapse whitespace, keeping tashkeel intact.

    This is the source's diacritic-handling contract: unlike
    :func:`src.utils.arabic.normalize_arabic` (which strips diacritics for the
    name-matching path), the diacritised matn is preserved verbatim apart from
    bidi-control noise and redundant whitespace.
    """
    return clean_whitespace(_BIDI_CONTROL_RE.sub("", text))


def _collection_name_from_path(csv_path: Path) -> str:
    """Derive a clean book slug from the file path.

    halimbahae filenames look like
    ``sahih_al-bukhari_ahadith_mushakkala_mufassala.utf8.csv``; we want the book
    slug (``sahih_al-bukhari``) so the loaded ``Collection`` node and the
    ``source_id`` namespace stay human-readable. Strip the ``.utf8`` suffix, then
    drop the ``_ahadith…`` descriptor tail (and, as a fallback, the diacritics
    markers).
    """
    stem = re.sub(r"\.utf8$", "", csv_path.stem, flags=re.I)
    book = re.split(r"_ahadith", stem, maxsplit=1, flags=re.I)[0]
    if book == stem:
        book = re.sub(
            r"[-_]?(mushakkala|mufassala|tashkeel|diacritics)",
            "",
            stem,
            flags=re.I,
        )
    return book.strip("-_ ") or stem


def run(raw_dir: Path, staging_dir: Path) -> list[Path]:
    """Parse halimbahae diacritised CSVs into hadith + collection Parquet.

    Emits ``hadiths_halimbahae.parquet`` and ``collections_halimbahae.parquet``
    (one ``Collection`` per book) so the graph load lands Hadith **and**
    Collection nodes and the ``APPEARS_IN`` edges resolve to a real target.
    """
    source_dir = raw_dir / "halimbahae"
    if not source_dir.exists():
        msg = f"Source directory not found: {source_dir}"
        raise FileNotFoundError(msg)

    all_csvs = list(source_dir.rglob("*.csv"))
    diacritics_csvs = [p for p in all_csvs if _DIACRITICS_RE.search(p.name)]
    if not diacritics_csvs:
        msg = f"No diacritised (mushakkala) CSVs found under {source_dir}"
        raise FileNotFoundError(msg)

    logger.info("halimbahae_csvs_found", count=len(diacritics_csvs))

    rows: list[dict[str, str | int | None]] = []
    # Preserve first-seen order of books, with a hadith count each, so the emitted
    # Collection rows mirror the books actually parsed.
    collection_counts: dict[str, int] = {}

    for csv_path in sorted(diacritics_csvs):
        collection = _collection_name_from_path(csv_path)
        try:
            # Headerless ``"<number>","<text>"`` rows — autogenerate column names
            # so the first data row is not consumed as a header.
            read_opts = pcsv.ReadOptions(autogenerate_column_names=True)
            table = pcsv.read_csv(str(csv_path), read_options=read_opts)
        except Exception:
            logger.warning("csv_read_failed", path=str(csv_path))
            continue

        if table.num_columns < 2:
            logger.warning("csv_too_few_columns", path=str(csv_path), columns=table.num_columns)
            continue

        # col 0 = hadith number, col 1 = diacritised text.
        number_vals = table.column(0).to_pylist()
        text_vals = table.column(1).to_pylist()

        for i in range(table.num_rows):
            hadith_num = safe_int(number_vals[i]) or (i + 1)
            raw_text = safe_str(text_vals[i])
            text_value = _clean_preserving_diacritics(raw_text) if raw_text else None
            source_id = generate_source_id(SOURCE_CORPUS, collection, hadith_num)

            rows.append(
                {
                    "source_id": source_id,
                    "source_corpus": SOURCE_CORPUS,
                    "collection_name": collection,
                    "book_number": None,
                    "chapter_number": None,
                    "hadith_number": hadith_num,
                    "matn_ar": None,
                    "matn_en": None,
                    "isnad_raw_ar": None,
                    "isnad_raw_en": None,
                    "full_text_ar": text_value,
                    "full_text_en": None,
                    "grade": None,
                    "chapter_name_ar": None,
                    "chapter_name_en": None,
                    "sect": SECT,
                }
            )

        collection_counts[collection] = collection_counts.get(collection, 0) + table.num_rows
        logger.info("halimbahae_csv_parsed", collection=collection, rows=table.num_rows)

    if not rows:
        msg = "No hadith rows parsed from halimbahae/Hadith"
        raise ValueError(msg)

    arrays = {field.name: [r[field.name] for r in rows] for field in HADITH_SCHEMA}
    out_table = pa.table(arrays, schema=HADITH_SCHEMA)

    hadith_path = staging_dir / "hadiths_halimbahae.parquet"
    write_parquet(out_table, hadith_path, schema=HADITH_SCHEMA)
    logger.info("halimbahae_parsed", total_hadiths=len(rows))

    # One Collection per parsed book, so APPEARS_IN edges resolve to a real node.
    collection_rows = [
        {
            "collection_id": generate_source_id(SOURCE_CORPUS, collection),
            "name_ar": None,
            "name_en": collection,
            "compiler_name": None,
            "compilation_year_ah": None,
            "sect": SECT,
            "total_hadiths": count,
            "source_corpus": SOURCE_CORPUS,
        }
        for collection, count in collection_counts.items()
    ]
    # Fill sourced name_ar + expected_count where curated (da#230).
    collection_rows = [apply_collection_metadata(r) for r in collection_rows]
    collection_arrays = {
        field.name: [r[field.name] for r in collection_rows] for field in COLLECTION_SCHEMA
    }
    collection_table = pa.table(collection_arrays, schema=COLLECTION_SCHEMA)
    collection_path = staging_dir / "collections_halimbahae.parquet"
    write_parquet(collection_table, collection_path, schema=COLLECTION_SCHEMA)
    logger.info("halimbahae_collections_parsed", count=len(collection_rows))

    return [hadith_path, collection_path]
